language: node_js
node_js:
- v8
deploy:
  provider: heroku
  app: dbusbot
  api_key:
    secure: ZhpCW/Oulu2ddmfsnesab4+bFf2zLe0h9Sk7Z/bWB1D0nMVBR59iuE+y4W68JD/RD9fm4FZDyCdf+S/wKOoXqtQQOumPy43qIWQNW2PBGNCugsFq+73rX5rWjX8SmBKokEueesEcej2tRQNr7wEdZYUWTcPvUAOx/ND40kNQjT5o5zQveO/43xFauOA4Ge1hkPku8hjG6ywqkReQSyiBv+FviN8XFDO1NQARK3MpPu+eFqRN9KSQrAcibUvtEFNbaAaDR4vfx02ZBcaaXMNTi7fjSl45LJzZYd2yaW06DpPOvQ5qN9cJTp6A7titeMR3cSTvIlniikL8k5Fbuf1Q6h8h4rG8gMy1GK/HBjkvhspqci/PbFUO1B/9zOiabTLyEkAO/hP2NQAWgGTjKFdZgUAOINp6+Ua3e4Z6IcHm4wWMNFVHMAVyeJlWirNhaV4bcBQD/aoaVYpgtqMvn5YEKIyfhoj4iZ4atsUbjHGw8Ruf82tpdCJXpi2m+MmNh7GKqv+7MdZufJ4PZpvnoEzBIIJc9xhjX4M18/d2ywdimaJsffkDJIvYxPpTGUgzFRnh8XNZxNgjsL2Nbir8PvijFK4TH+7A5EaKx81xdHaZ9yxReb8EwO0ICXz/+dqT8alXk1H+P+10dvMGslbDhXFeen5oRqPYZqrBTjMUSt6/ZDA=
